config/routes.rb
Rails.application.routes.draw do

  # Only Admin users can access the sidekiq dashboard
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Homepage
  root to: 'pages#home'

  # Certificate in html to convert to pdf
  get 'certificate/user/:id', to: 'pages#certificate'
  # Download pdf link
  get :download_certificate, to: 'pages#download_certificate'

  # Required by twitter api
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'

  # Page with forest map
  # get 'foret-groot', to: 'pages#forest'

  # Stress test
  # get 'loaderio-51b2f97f3c21b82ca26cc5f95eebf17d', to: 'pages#stress_test' 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :user, optional: true
  validates :picture_link, presence: true

  def self.last_turned
    where(last_turned: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  has_one :card
  after_create :unlock_a_card

  def unlock_a_card
    card = Card.where(turned: false).order("RANDOM()").first
    # reset last_turned card to false
    reset_last_turned
    unless card.nil?
      user_count = User.count
      # generate the tree_id with prefix
      tree_id = generate_tree_id(user_count)
      card.update(turned: true, last_turned: true, tree_id: tree_id, user: self)
      self.update(tree_count: user_count, congratulation: true)
      UserMailer.email_certificate(self.id).deliver_later(wait: 2.seconds)
    else
      flash.notice = "Tous les groots ont été plantés ! Rdv dans les salles le 28 avril."
    end
  end

  def self.find_for_twitter_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :name, :nickname)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end
    return user
  end

  private

  def reset_last_turned
    last_turned_card = Card.where(last_turned: true)
    unless last_turned_card.nil?
      last_turned_card.update(last_turned: false)
    end
  end

  # generate the tree_id number for certificate
  def generate_tree_id(count)
    if count < 10
      "000#{count}"
    elsif count >= 10 && count < 100
      "00#{count}"
    elsif count >= 100 && count < 1000
      "0#{count}"
    else
      "#{count}" 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def default_url_options
  { host: ENV['HOST'] || 'localhost:3000' }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :certificate, :privacy, :terms, :wait ]

  def home
    @cards = Card.order(:id)
    @turned_counter = Card.where(turned: true).count
    @grid_colors = ["grid_color_1.jpg", "grid_color_2.jpg", "grid_color_3.jpg", "grid_color_4.jpg", "grid_color_1.jpg", "grid_color_2.jpg", "grid_color_3.jpg"]
  end

  # def wait 
  # end
  
  # HTML certificate to convert to pdf
  # The navbar is escaped in that view cf:layout
  def certificate
    @user = User.find(params[:id])
  end

  def download_certificate
    @user = current_user
    pdf = WickedPdf.new.pdf_from_url("#{ENV["PDF_URL"]}#{@user.id}")
    send_data pdf, filename: "certificate_#{@user.card.tree_id}.pdf", type: "application/pdf", disposition: "attachment"
  end

  # Required by twitter
  def privacy
    @turned_counter = Card.where(turned: true).count
  end

  def terms
    @turned_counter = Card.where(turned: true).count
  end

  # Forest map
  # def forest
  # end

  # Stress test
  # def stress_test
  # end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    user = User.find_for_twitter_oauth(request.env['omniauth.auth'])

    if user.persisted?
      # unless user.congratulation
      #   flash.notice = "Vous avez déjà planté le groot #{user.card.tree_id}! Bravo vous avez participé à sauver notre galaxie ! "
      # end
      sign_in_and_redirect user
    else
      flash.notice = "Votre authentifaction twitter a échoué pour une raison mystérieuse, mais vous pouvez ré-essayer !"
      redirect_to root_path
    end
  end

  def failure
    # We can put a flash message here for user that refuses twitter connect
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" contentetat="summary">
    
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image" content="<%= DEFAULT_META["meta_image_twitter"] %>">

    <!-- <meta property="og:type" content="website" /> -->
    

    <!-- Twitter -->
<!--     <meta name="twitter:site" content="<%#= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%#= meta_title %>">
    <meta name="twitter:description" content="<%#= meta_description %>">
    <meta name="twitter:creator" content="<%#= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image" content="<%#= DEFAULT_META["meta_image_twitter"] %>"> -->
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <!-- Escape the navbar for the certificate view -->
    <% unless action_name == 'certificate' %>
      <%= render 'shared/navbar' %>
    <% end %>
      <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/_congratulation.html.erb
<div class="modal fade groot-modal" id="congratulation" tabindex="-1" role="dialog">
  <div class="modal-dialog groot-modal-dialog" role="document">
    <div class="modal-content groot-modal-content">
      <div class="modal-header groot-modal-header">
        <button type="button" class="close groot-modal-close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="groot-modal-title">FÉLICITATIONS !</h4>
      </div>
      <div class="groot-modal-body">
        <p>Vous devenez membre des Gardiens de notre Galaxie ! Votre certificat personnel et le fichier de géolocalisation de la forêt Groot vous ont été envoyés par email.</p>
      </div>
      <div class="groot-modal-footer">
        <h4>INVITEZ VOS AMIS À DEVENIR EUX AUSSI LES GARDIENS DE NOTRE GALAXIE !</h4>
        <h6>#GardiensdelaGalaxie2 #JournéedelaTerre</h6>
        <div class="modal-share-congrats"><%= social_share_button_tag(meta_title, 'data-twitter-title' => "Devenez les Gardiens de notre Galaxie en plantant un Groot pour la #JournéedelaTerre #GardiensdelaGalaxie2 Rdv sur:", desc: meta_description) %></div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="fixed-container">

<div class="col-xs-13 col-md-13 col-lg-5 col-lg-push-4 grid-col-style">
  <div class="grid">
    <% if @turned_counter == 2000 %>
      <div class="full-image">
        <%= image_tag "guardian.jpg" %>
      </div>
    <% else %>
      <% @cards.each do |card|%>
        <% if card.last_turned %>
          <div class="card grid-cache-last-turned" id="<%= card.id %>">
            <%= image_tag card.picture_link %>
          </div>
        <% elsif card.turned %>
          <div class="card" id="<%= card.id %>">
            <%= image_tag card.picture_link %>
          </div>
        <% else %>
          <div class="card grid-cache-bordered" id="<%= card.id %>">
            <%= image_tag @grid_colors.sample %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="col-xs-13 col-md-13 col-lg-4 col-lg-pull-5 project-font project-style">
  <!-- The following div is used as anchor for the scroll on XS -->
  <div id="project"></div>

  <div class="inner">
    <h1 class="project-font-title">DEVENEZ LES GARDIENS DE NOTRE GALAXIE !</h1>
    <p class="project-emphasized-text">2 000 « GROOT » vont être plantés en cette Journée Internationale de la Terre, et nous vous donnons l’occasion de parrainer le vôtre.</p>
    <p class="project-font-text">Vous recevrez <span class="project-emphasized-text-inside">votre certificat de plantation unique et nominatif</span> ainsi qu’un fichier de géolocalisation de l’emplacement de votre Groot. Pour cela rien de plus simple, il suffit d’avoir un compte Twitter et de se connecter en cliquant sur le bouton <%= link_to 'Plantez votre groot', new_user_registration_path, :remote => true, 'data-toggle' => "modal", 'data-target' => "#twitter_modal", method: 'get', class:'groot-button-link'%>.</p>
    <p class="project-font-text">
    La totalité des arbres est financé par Marvel Studios dans le cadre de la sortie des Gardiens de la Galaxie Vol.2 au cinéma.</p>
    <p class="project-font-text"><span class="project-emphasized-text-inside">Les arbres sont plantés en Amazonie</span> péruvienne, selon le modèle de l'agroforesterie qui consiste à combiner agriculture et plantation d'arbres et qui présente de nombreux bénéfices : érosion, sécheresse et inondation évitées, retour de biodiversité, séquestration carbone dans les arbres et conservation de la forêt.</p>
    <p class="project-font-text"><span style="color:#e7e3ed">
    Le projet de l'Alto Huayabamba permet ainsi d'éviter la déforestation, fortement liée à l'agriculture intensive en Amazonie, en proposant un modèle plus pérenne et respectueux de l'écosystème.</span></p>
    <p class="project-emphasized-text">Participez à cette opération en plantant vous aussi un Groot, et devenez les Gardiens de notre Galaxie !</p>
  </div>
</div>

<div class="col-lg-4 visible-lg no-padding-side">
  <div class="timeline-style">
  <div class="inner-timeline">
  <a class="twitter-timeline"
  href="https://twitter.com/hashtag/GardiensdelaGalaxie2"
  data-lang="fr"
  data-theme="light"
  data-height="665px"
  data-chrome="transparent, noheader, noborders, noscrollbar"
  data-border-color="#00001f"
  data-link-color="#de723a"
  data-widget-id="855378581903609857">Tweets sur #GardiensdelaGalaxie2</a>
  </div>
  </div>
</div>
</div>

<div class="footer">
  <div class="footer-left footer-logo"><%= image_tag("LogoPP.png", size: "65x15") %></div>
  <div class="footer-right">
    <div class= "footer-item"><%= link_to "Termes et Conditions", privacy_path %></div>
    <div class="footer-item">
    <%=mail_to "purprojet@planter-un-arbre.com", "Contact",
           subject: "A propos de Groot"%>
    </div>
    </div>
</div>


<!-- Modal connect with twitter -->
  <%= render "devise/registrations/new" %>

<!-- Congratulation card  -->
  <% if user_signed_in? && current_user.congratulation %>
    <%= render "pages/congratulation" %>
  <% end %>


<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/pages/privacy.html.erb
<div class="container policy">
<div class="return-home"><u><%= link_to "Home", root_path %></u> > Conditions d'utilisation et Politique de confidentialité</div>
  <h1>CONDITIONS D’UTILISATION & POLITIQUE DE CONFIDENTIALITE</h1>
    <h2>CONDITIONS D’UTILISATION</h2>
        <p>
        Merci de votre visite sur le Site plantez-un-groot.fr. Ce Site vous propose de soutenir la plantation d’arbres en Amazonie, à l’occasion de la Journée de la Terre 2017 et de la sortie du film Les Gardiens de La Galaxie Vol 2 de Marvel Studios. Les arbres sont plantés par PUR PROJET, une entreprise qui développe et suit des projets de reforestation et de conservation forestière. Le Site est édité par la société 4U Abel SAS. L'utilisation du Site implique votre acceptation des présentes Conditions d’Utilisation. Nous vous invitons à les lire attentivement. Elles ont pour objet l'encadrement juridique des modalités de mise à disposition des services du Site plantez-un-groot.fr et leur utilisation par l'Utilisateur.
        </p>
        <p>
        Les conditions générales d'utilisation doivent être acceptées par tout Utilisateur souhaitant accéder au Site. Elles constituent le contrat entre le Site et l'Utilisateur. L’accès au Site par l’Utilisateur signifie son acceptation des présentes conditions générales d’utilisation. En cas de non-acceptation des conditions générales d'utilisation stipulées dans le présent contrat, l'Utilisateur se doit de renoncer à l'accès des services proposés par le Site.
        Le Site plantez-un-groot.fr se réserve le droit de modifier unilatéralement et à tout moment le contenu des présentes conditions générales d'utilisation.
        </p>
      <h3>Accès aux services</h3>
        <p>
        Le Site permet à l'Utilisateur de parrainer gratuitement la plantation d’un arbre en Amazonie, dans la limite d’un arbre par utilisateur et de 2000 arbres au total. La totalité des arbres est financé par Marvel Studios dans le cadre de la sortie des Gardiens de la Galaxie Vol.2 au cinéma.
        L’accès au parrainage d’un arbre implique que l’Utilisateur s’identifie sur le Site via son compte twitter. Un email sera alors envoyé à l’adresse email liée au compte twitter de l’Utilisateur, avec le certificat de plantation unique d’un arbre - dont le nom d’attribution sera le pseudo twitter de l’Utilisateur- , et un fichier de géolocalisation de la parcelle de plantation à ouvrir avec le programme Google Earth.
        </p>
        <p>
        Le Site est accessible gratuitement en tout lieu à tout Utilisateur ayant un accès à Internet. Tous les frais supportés par l'Utilisateur pour accéder au service (matériel informatique, logiciels, connexion Internet, etc.) sont à sa charge.
        Le Site met en œuvre tous les moyens mis à sa disposition pour assurer un accès de qualité à ses services. L'obligation étant de moyens, le Site ne s'engage pas à atteindre ce résultat.
        Tout événement dû à un cas de force majeure ayant pour conséquence un dysfonctionnement du réseau ou du serveur n'engage pas la responsabilité de plantez-un-groot.fr.
        </p>
      <p>
      L'accès aux services du Site peut à tout moment faire l'objet d'une interruption, d'une suspension, d'une modification sans préavis pour une maintenance ou pour tout autre cas. L'Utilisateur s'oblige à ne réclamer aucune indemnisation suite à l'interruption, à la suspension ou à la modification du présent contrat.
      </p>

    <h3>Utilisation et contenu</h3>
      <p>
      Le Site n’est destiné qu’à un usage personnel. Vous n’êtes pas autorisé à utiliser le Site à des fins commerciales ou de toute manière qui soit illégale ou qui porterait préjudice au Site ou à toute autre personne ou entité, comme déterminé à notre seule discrétion.
      </p>
      <p>
      L’ensemble des informations, documents, fonctions, marques, logos, signes et tous autres contenus et applications présents sur le Site font l'objet d'une protection par le Code de la propriété intellectuelle et plus particulièrement par le droit d'auteur.
      L'Utilisateur sollicite l'autorisation préalable et écrite du Site pour toute reproduction, publication, copie des différents contenus.
      </p>
      <p>
      Les pages web vers lesquelles pointent les liens hypertextes présent sur le Site n’engagent en rien la responsabilité de plantez-un-groot.fr qui n’a pas le contrôle de ces pages et de leur contenu. L'Utilisateur s'interdit donc à engager la responsabilité du Site concernant le contenu et les ressources relatives à ces liens hypertextes sortants.
      </p>

    <h3>Comptes et Données personnelles</h3>
      <p>
      Les informations demandées à l’inscription au Site, par le biais du twitter connect, sont nécessaires et obligatoires pour la création du compte de l'Utilisateur. En particulier, l'adresse électronique qui sera utilisée pour envoyer le certificat de plantation et le fichier de géolocalisation de la parcelle de plantation.
      </p>
      <p>
      L’Utilisateur accepte de fournir et de maintenir ses informations personnelles vraies, exactes, à jour et complètes. L’Utilisateur ne prétend pas être toute autre personne ou entité ou ne représente pas son identité ou une affiliation avec toute personne ou entité de manière inexacte, y compris en utilisant le nom d’utilisateur, le mot de passe ou toute autre information relative au compte de quelqu’un d’autre.
      </p>
      <p>
      L’Utilisateur accepte d’aviser le Site dans les plus brefs délais à l’adresse email indiquée sur le footer du Site de toute utilisation non-autorisée des informations relatives à son compte ou de toute autre violation de sécurité concernant ou impliquant ce Site dont il prendrait connaissance. En outre, l’Utilisateur accepte de se déconnecter à la fin de chaque session.
      </p>
      <p>
      Le Site assure à l'Utilisateur une collecte et un traitement d'informations personnelles dans le respect de la vie privée conformément à la loi n°78-17 du 6 janvier 1978 relative à l'informatique, aux fichiers et aux libertés.
      En vertu des articles 39 et 40 de la loi en date du 6 janvier 1978, l'Utilisateur dispose d'un droit d'accès, de rectification, de suppression et d'opposition de ses données personnelles. L'Utilisateur exerce ce droit via l’adresse email présente dans le footer du Site.
      </p>

    <h3>Responsabilité et force majeure</h3>
      <p>
      L'Utilisateur s'assure de garder son mot de passe secret. Toute divulgation du mot de passe, quelle que soit sa forme, est interdite.
      L'Utilisateur assume les risques liés à l'utilisation de son identifiant et mot de passe. Le Site décline toute responsabilité.
      Tout usage du service par l'Utilisateur ayant directement ou indirectement pour conséquence des dommages doit faire l'objet d'une indemnisation au profit du Site.
      Le Site s'engage à mettre en œuvre tous les moyens nécessaires afin de garantir au mieux la sécurité et la confidentialité des données.
      La responsabilité du Site ne peut être engagée en cas de force majeure ou du fait imprévisible et insurmontable d'un tiers.
      </p>
      <p>
      Le Site se réserve à tout moment le droit de modifier les clauses stipulées dans le présent contrat.
      La législation française s'applique au présent contrat.
      </p>

  <h2>POLITIQUE DE CONFIDENTIALITE</h2>
      <p>
      Les données personnelles sont collectées par l’éditeur du site plantez-un-groot.
      Les présentes règles de confidentialité visent à vous indiquer quelles informations sont collectées, pour quelle raison, et comment elles sont utilisées.
      </p>
    <h3>Données collectées & Finalité</h3>
      <p>
      Pour parrainer un arbre sur le Site, l’Utilisateur s’authentifie avec le service tiers Twitter Connect. Les informations de contact de l’Utilisateur, liées à son compte Twitter, sont alors collectées.
      Seules les données de contacts sont collectées, et uniquement lors de l’authentifaction avec Twitter.
      Le Site ne collecte aucune donnée sensible, à savoir aucune donnée relative aux origines raciales ou ethniques, aux opinions politiques, philosophiques ou religieuses ou à l’appartenance syndicale, ou à la santé ou la vie sexuelle de l’Utilisateur.
      </p>
      <p>
      Les données collectées sont utilisées pour associer l’Utilisateur à la plantation d’un arbre, et pour lui envoyer par email son certificat de plantation personnalisé et le fichier de géolocalisation de la parcelle de plantation.
      Les données collectées ne seront pas exploitées d’autre façon, ni transmises à des sociétés tierces.
      </p>
    <h3>Questions, Droit de suppression</h3>
      <p>
      Pour toute questions ou pour exercer votre droit de suppressions des données personnelles, vous pouvez nous contacter à l’adresse email indiquée dans le footer du site.
      </p><br><br>
</div>

<!-- Modal connect with twitter -->
  <%= render "devise/registrations/new" %>

<!-- footer -->
<div class="footer">
  <div class="footer-left footer-logo"><%= image_tag("LogoPP.png", size: "65x15") %></div>
  <div class="footer-right">
    <div class= "footer-item"><%= link_to "Termes et Conditions", privacy_path %></div>
    <div class="footer-item">
    <%=mail_to "purprojet@planter-un-arbre.com", "Contact",
           subject: "A propos de Groot"%>
    </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-groot">
<!-- USER SIGNED-IN -->
  <% if user_signed_in? %>
  <!-- DESKTOP - NAVBAR LEFT - USER SIGNED-IN :-->
    <div class="navbar-left hidden-xs hidden-sm hidden-md">
      <div class="navbar-item-left ">
        <div class="dropdown">
          <div class="class dropdown-toggle navbar-small-text cursor-nickname" id="navbar-groot-menu" data-toggle="dropdown"><%= current_user.nickname.nil? ? "Gardien" : current_user.nickname %></div>
          <ul class="dropdown-menu dropdown-menu-right navbar-groot-dropdown-menu">
            <li><%= link_to "Télécharger le certificat", download_certificate_path %></li>
            <!-- <li><%#= link_to "Voir la forêt Groot", foret_groot_path %></li> -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

  <!-- MOBILE - LEFT DROPDOWN LIST - USER SIGNED-IN : -->
    <div class="navbar-left navbar-item-mobile hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu navbar-groot-dropdown-menu">
          <li><%= link_to "Découvrir le projet", '#project'%></li>
          <li><%= link_to "Télécharger mon certificat", download_certificate_path %></li>
          <li id="inside-dropdown"><a>Partager :<%= social_share_button_tag(meta_title, 'data-twitter-title' => "Devenez les Gardiens de notre Galaxie en plantant un Groot pour la #JournéedelaTerre #GardiensdelaGalaxie2 Rdv sur:", desc: meta_description) %></a></li>
          <li><%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
          <% end %>
          </li>
        </ul>
      </div>
    </div>

  <!-- CENTER - USER SIGNED-IN     -->
  <div class="navbar-center">
    <p class="navbar-btn-planted">Merci d'avoir planté Groot <%= current_user.tree_count %> !</p>
  </div>

  <!-- DESKTOP - NAVBAR RIGHT -USER SIGNED-IN-->
  <div class="navbar-right">
      <div class="navbar-item-box-right hidden-xs hidden-sm hidden-md">
        <p class="navbar-small-text ">Partager :</p>
        <%= social_share_button_tag(meta_title, 'data-twitter-title' => "Devenez les Gardiens de notre Galaxie en plantant un Groot pour la #JournéedelaTerre #GardiensdelaGalaxie2 Rdv sur:", desc: meta_description) %>
      </div>
  </div>
  <% else %>
<!-- USER SIGNED-OUT -->
  <!-- DESKTOP - NAVBAR LEFT - USER SIGNED-OUT -->
    <div class="navbar-left hidden-xs hidden-sm hidden-md">
      <div class="navbar-item-left">
        <%#= link_to "Mon Certificat (login)", user_twitter_omniauth_authorize_path%>
      </div>
    </div>

  <!-- MOBILE - LEFT DROPDOWN LIST - USER SIGNED-OUT -->
    <div class="navbar-left navbar-item-mobile hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu navbar-groot-dropdown-menu">
          <li><%= link_to "Découvrir le projet", '#project' %></li>
          <li id="inside-dropdown"><a>Partager: <%= social_share_button_tag(meta_title, 'data-twitter-title' => "Devenez les Gardiens de notre Galaxie en plantant un Groot pour la #JournéedelaTerre #GardiensdelaGalaxie2 Rdv sur:", desc: meta_description) %></a></li>
          <li><%#= link_to "Mon certificat (login)", user_twitter_omniauth_authorize_path %></li>
          <!-- <li><%#= link_to "Me connecter", user_twitter_omniauth_authorize_path %><i class="fa fa-user nimporte"></i></li> -->
          <!-- <li><%#= link_to " Me connecter", user_twitter_omniauth_authorize_path, class:"fa fa-user" %></li> -->
        </ul>
      </div>
    </div>
  <!-- CENTER - USER SIGNED-OUT     -->
    <div class="navbar-center">
      <%= link_to 'Plantez votre Groot', new_user_registration_path, :remote => true, 'data-toggle' => "modal", 'data-target' => "#twitter_modal", method: 'get', :class => 'navbar-btn-plant' %>
    </div>

  <!-- DESKTOP - NAVBAR RIGHT -USER SIGNED-OUT-->
  <div class="navbar-right">
      <div class="navbar-item-box-right hidden-xs hidden-sm hidden-md">
      </div>
  </div>
  <% end %>
</div>